name: pipenv-update
on:
  schedule:
    - cron:  '8 22 * * 1'
  workflow_dispatch:

jobs:
  pipenv-update:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
          python-version: 3.7
      - run: |
          python -m pip install --upgrade pipenv wheel
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pipenv  --python 3.7 update
          git add -u
          git commit -m "update pipenv packages"
        env:
          GITHUB_TOKEN: ${{ github.PAT_TOKEN }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: '[AUTO-PR] Update pipenv packages'
          body: |
            bump pipenv packages
            - Auto-generated by [pipenv-update github action](https://github.com/bridgecrewio/airiam/blob/master/.github/workflows/pipenv-update.yml)
          labels: automated pr
          branch: pipenvfix
          branch-suffix: timestamp
