name: Unit tests

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
      - name: Set up Python 3.9
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5
        with:
          python-version: 3.9
      - uses: dschep/install-pipenv-action@aaac0310d5f4a052d150e5f490b44354e08fbb8c  # v1
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Test with pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pipenv run python -m coverage run -m pytest
          pipenv run python -m coverage report
          pipenv run python -m coverage html