name: Unit tests

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Set up Python 3.7
        uses: actions/setup-python@0f07f7f756721ebd886c2462646a35f78a8bc4de # v1
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@aaac0310d5f4a052d150e5f490b44354e08fbb8c # v1
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Test with pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pipenv run python -m coverage run -m pytest
          pipenv run python -m coverage report
          pipenv run python -m coverage html